version: "3"
x-aws-vpc: "vpc-0c9369fad1e29217c" ##TODO、VPC指定
services:
  backend:
    container_name: todo-app-backend
    build: 
      context: . # docker build コマンドを実行する場所
      dockerfile: ./docker/Dockerfile.backend
    # image: todo-app-backend
    image: 056267658604.dkr.ecr.ap-northeast-1.amazonaws.com/minipj/todo-app-backend #TODO、ECRにpush&参照
    # -j4 並列処理をするコマンド 
    command: |
      bash -c "rm -f tmp/pids/server.pid &&
      bin/rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails s -p 4000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 4000:4000

  frontend:
    container_name: todo-app-frontend
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    image: 056267658604.dkr.ecr.ap-northeast-1.amazonaws.com/minipj/todo-app-frontend #TODO、ECRにpush&参照
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - 3000:3000
    command: "yarn run dev"
