default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# dbをrdsに切り替え
development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: todo-calendar_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

# test:
#   <<: *default
#   database:  todo-calendar_test
#   host: <%= ENV['DB_HOST'] || 'db' %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: todo-app_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>